### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by owcxe** [AfoninZ/MultiMC5-Cracked#72] opened 2021-09-21 16:24 UTC
### Operating System

Linux

### Description of bug

My linux distro is Debian 11.
I have installed: **clang-11, clang, zlib1g-dev, libgl1-mesa-dev, openjdk-8-jdk.**

Qt5 compiler was installed from repo, also Debian 11 haven't **qt5-default** package, so im only installed it's dependencies. (**qtbase5-dev, qtchooser, qt5-qmake, qtbase5-dev-tools**) and it should work.

After `cmake -DCMAKE_INSTALL_PREFIX=../install ../src` command there is no errors.
When im doing `cmake -DCMAKE_INSTALL_PREFIX=../install ../src` command it's building fine until about 79-80%  is done, and this happening:

![изображение](https://user-images.githubusercontent.com/91143694/134201705-a7938217-225b-42d5-8aba-9d470e4239c0.png)

Im also compiled the original MultiMC5 today from sources and it was working.

P.S. What about project's own discord server?

### Steps to reproduce

git clone https://github.com/AfoninZ/MultiMC5-Cracked.git
git submodule init
git submodule update
mkdir ~/MultiMC && cd ~/MultiMC
mkdir build
mkdir install
git clone --recursive https://github.com/AfoninZ/MultiMC5-Cracked.git src
cd build
cmake -DCMAKE_INSTALL_PREFIX=../install ../src
make -j5 install

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AndreVuillemot160** [comment] 2021-09-23 14:12
Probably duplicate of https://github.com/AfoninZ/MultiMC5-Cracked/issues/61

**Closed** 2021-10-07 18:12 UTC
Labels: bug
