### ISSUE TITLE
Can't log in with Ely.By account.

### ISSUE THREAD

**Issue by literally-Zak** [AfoninZ/MultiMC5-Cracked#151] opened 2022-01-22 19:21 UTC
### Operating System

Linux

### Description of bug

When trying to log in with an **Ely.By account**, it doesn't work.

![issueultimmc](https://user-images.githubusercontent.com/98234074/150652865-7ae3e1c9-1064-4e08-b9f8-15ab7afa40c3.png)

### Steps to reproduce

- Open UltimMC
- Add a new account with Ely.By

### Suspected cause

I don't know.

**Comment by J1Github** [comment] 2022-01-23 10:06
I have the same issue on mac

**Comment by Ka1dz0** [comment] 2022-01-23 10:06
Duplicate of #148

**Closed** 2022-01-25 22:21 UTC
Labels: bug
