### ISSUE TITLE
Update system breaks the launcher

### ISSUE THREAD

**Issue by ReinDoesGit** [AfoninZ/MultiMC5-Cracked#118] opened 2021-11-25 12:06 UTC
### Operating System

Windows

### Description of bug

The launcher's update system is breaking the launcher

### Steps to reproduce

- Open UltimMC
- Click Update Now
- Launcher dosen't respond anymore

### Suspected cause

My Launcher is outdated

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ReinDoesGit** [comment] 2021-11-25 12:11
Installing the latest version seems to have done something, but after a little bit, It just dosen't respond anymore

**Comment by Slddev** [comment] 2021-11-25 14:23
> Installing the latest version seems to have done something, but after a little bit, It just dosen't respond anymore

Do not use the update system since it uses the original MultiMC files.

**Comment by Slddev** [comment] 2021-11-25 14:24
#30

**Comment by Sebastian-byte** [comment] 2021-11-26 02:28
Duplicate of #30

**Closed by Sebastian-byte** 2021-11-26 02:28 UTC
Labels: bug
