### ISSUE TITLE
Builds are failing.

### ISSUE THREAD

**Issue by TDSorcerer** [AfoninZ/MultiMC5-Cracked#74] opened 2021-09-26 14:12 UTC
### Operating System

Windows

### Description of bug

Builds are failing in "actions" in GitHub resulting in us not being able to update to newer versions of MultiMC - Cracked
Log output:
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\launcher\dialogs\LoginDialog.cpp: In constructor 'LoginDialog::LoginDialog(QWidget*)':
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\launcher\dialogs\LoginDialog.cpp:32:9: error: 'm_radioButtons' was not declared in this scope
         m_radioButtons[provider->id()] = button;
         ^
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\launcher\dialogs\LoginDialog.cpp:35:5: error: 'm_radioButtons' was not declared in this scope
     m_radioButtons["dummy"]->setChecked(true);
     ^
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\launcher\dialogs\LoginDialog.cpp: In member function 'virtual void LoginDialog::accept()':
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\launcher\dialogs\LoginDialog.cpp:54:26: error: 'm_radioButtons' was not declared in this scope
     for(auto providerId: m_radioButtons.keys()){
                          ^
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\launcher\dialogs\LoginDialog.cpp:56:24: error: 'class MinecraftAccount' has no member named 'setProvider'
             m_account->setProvider(AuthProviders::lookup(providerId));
                        ^
mingw32-make[2]: *** [launcher/CMakeFiles/MultiMC_logic.dir/dialogs/LoginDialog.cpp.obj] Error 1
launcher\CMakeFiles\MultiMC_logic.dir\build.make:3969: recipe for target 'launcher/CMakeFiles/MultiMC_logic.dir/dialogs/LoginDialog.cpp.obj' failed
mingw32-make[2]: *** Waiting for unfinished jobs....
mingw32-make[1]: *** [launcher/CMakeFiles/MultiMC_logic.dir/all] Error 2
CMakeFiles\Makefile2:2024: recipe for target 'launcher/CMakeFiles/MultiMC_logic.dir/all' failed
mingw32-make: *** [all] Error 2
makefile:144: recipe for target 'all' failed
Error: Process completed with exit code 2.

### Steps to reproduce

See in "actions" Github page. The newer actions are failing and there are warning signs.

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by owcxe** [comment] 2021-09-27 15:21
Duplicate of #72

**Closed** 2021-10-07 18:11 UTC
Labels: bug
